# Generated by Django 3.1.2 on 2020-12-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_remove_user_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='peopleWhoLike', to='network.Comment'),
        ),
    ]
