# Generated by Django 3.1.2 on 2020-12-07 15:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_comment_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='_user_following_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
