# Generated by Django 3.1.2 on 2020-12-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_user_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='editTimestamp',
            field=models.DateTimeField(blank=True, default=0, null=True),
        ),
    ]
