# Generated by Django 3.1.2 on 2020-12-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20201219_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='editTimestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
